"""
Veliora.AI — Selfie Compositing Service
Uses HuggingFace Serverless API for face-preserving image generation.
MVP: Bot selfies only. User composite code is commented out for future use.
"""

import httpx
import base64
import logging
import uuid
from typing import Optional
from config.settings import get_settings
from config.mappings import get_bot_face_image
from services.supabase_client import upload_to_storage, get_public_url

logger = logging.getLogger(__name__)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# BOT SELFIE GENERATION (MVP — Bot face only)
# Uses text-to-image with scene description from Gemini
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

async def generate_bot_selfie(
    bot_id: str,
    scene_description: str,
    user_id: str,
) -> Optional[dict]:
    """
    Generate a contextual selfie of the bot using HuggingFace Serverless API.
    
    MVP approach: Use text-to-image with the scene description.
    The bot's face image is referenced as a style/identity hint in the prompt.
    
    Args:
        bot_id: The persona identifier
        scene_description: Generated by Gemini from chat context
        user_id: For storage path
    
    Returns: {"image_url": str, "scene_description": str}
    """
    settings = get_settings()

    # Build the generation prompt
    # Include persona details for consistent character generation
    persona_prompt = _build_persona_visual_prompt(bot_id)
    full_prompt = (
        f"{persona_prompt}, {scene_description}, "
        f"selfie angle, looking at camera, natural lighting, "
        f"high quality portrait photography, realistic"
    )

    url = f"https://api-inference.huggingface.co/models/{settings.HF_IMAGE_MODEL}"
    headers = {"Authorization": f"Bearer {settings.HF_API_TOKEN}"}
    payload = {"inputs": full_prompt}

    try:
        async with httpx.AsyncClient(timeout=120.0) as client:
            response = await client.post(url, headers=headers, json=payload)

            # Handle model loading (cold start)
            if response.status_code == 503:
                logger.info("HF image model loading, retrying in 20s...")
                import asyncio
                await asyncio.sleep(20)
                response = await client.post(url, headers=headers, json=payload)

            response.raise_for_status()
            image_bytes = response.content

        # Upload to Supabase Storage
        filename = f"selfies/{user_id}/{bot_id}/{uuid.uuid4().hex}.png"
        image_url = await upload_to_storage(
            "selfies", image_bytes, filename, "image/png"
        )

        return {
            "image_url": image_url,
            "scene_description": scene_description,
        }

    except Exception as e:
        logger.error(f"Bot selfie generation failed: {e}")
        return None


def _build_persona_visual_prompt(bot_id: str) -> str:
    """
    Build a visual description of the persona for consistent image generation.
    Maps bot_id to a physical description for the text-to-image prompt.
    """
    # Visual descriptions for consistent character generation
    persona_visuals = {
        # Delhi personas
        "delhi_mentor_male": "distinguished Indian man, 50 years old, salt and pepper hair, warm eyes, wearing elegant kurta",
        "delhi_mentor_female": "elegant Indian woman, 50 years old, graceful features, wearing silk saree",
        "delhi_friend_male": "young Indian man, 23 years old, stylish haircut, casual streetwear, cool demeanor",
        "delhi_friend_female": "young Indian woman, 23 years old, trendy outfit, confident expression",
        "delhi_romantic_male": "handsome Indian man, 29 years old, well-groomed, wearing smart casual clothes",
        "delhi_romantic_female": "beautiful Indian woman, 29 years old, elegant features, stylish outfit",

        # Japanese personas
        "japanese_mentor_male": "distinguished Japanese man, 60 years old, wise expression, traditional Japanese clothing",
        "japanese_mentor_female": "elegant Japanese woman, 60 years old, gentle features, traditional kimono",
        "japanese_friend_male": "young Japanese man, 25 years old, trendy hairstyle, Kapital jacket, cool vibe",
        "japanese_friend_female": "young Japanese woman, 25 years old, auburn hair, dango bun, vintage tee",
        "japanese_romantic_male": "handsome Japanese man, 30 years old, sharp suit, Rolex watch, refined look",
        "japanese_romantic_female": "beautiful Japanese woman, 30 years old, oversized sweater, warm smile",

        # Parisian personas
        "parisian_mentor_male": "distinguished French man, 60 years old, silver hair, elegant suit, Parisian charm",
        "parisian_mentor_female": "elegant French woman, 60 years old, sophisticated style, classic Parisian fashion",
        "parisian_friend_male": "young French man, 25 years old, vintage bomber jacket, Doc Martens, artistic vibe",
        "parisian_friend_female": "young French woman, 25 years old, chic bohemian style, beret, artistic flair",
        "parisian_romantic_female": "beautiful French woman, 28 years old, red lipstick, elegant dress, romantic aura",

        # Berlin personas
        "berlin_mentor_male": "distinguished German man, 55 years old, intellectual look, modern European style",
        "berlin_mentor_female": "elegant German woman, 55 years old, refined style, contemporary fashion",
        "berlin_friend_male": "young German man, 25 years old, creative look, Berlin street fashion",
        "berlin_friend_female": "young German woman, 25 years old, edgy style, Berlin creative scene vibe",
        "berlin_romantic_male": "handsome German man, 30 years old, stylish, warm expression",
        "berlin_romantic_female": "beautiful German woman, 28 years old, chic outfit, warm eyes",

        # Singapore personas
        "singapore_mentor_male": "distinguished Singaporean man, 50 years old, professional attire, wise demeanor",
        "singapore_mentor_female": "elegant Singaporean woman, 50 years old, modern Asian style, refined look",
        "singapore_friend_male": "young Singaporean man, 25 years old, casual smart style, energetic",
        "singapore_friend_female": "young Singaporean woman, 25 years old, trendy outfit, vibrant personality",
        "singapore_romantic_male": "handsome Singaporean man, 28 years old, well-dressed, charming smile",
        "singapore_romantic_female": "beautiful Singaporean woman, 27 years old, elegant style, warm expression",

        # Mexican personas
        "mexican_mentor_male": "distinguished Mexican man, 50 years old, warm features, traditional Mexican style",
        "mexican_mentor_female": "elegant Mexican woman, 50 years old, colorful clothing, warm personality",
        "mexican_friend_male": "young Mexican man, 25 years old, casual style, friendly expression",
        "mexican_friend_female": "young Mexican woman, 25 years old, boho-chic style, vibrant personality",
        "mexican_romantic_male": "handsome Mexican man, 30 years old, stylish outfit, charming expression",
        "mexican_romantic_female": "beautiful Mexican woman, 28 years old, embroidered blouse, warm smile",

        # Sri Lankan personas
        "srilankan_mentor_male": "distinguished Sri Lankan man, 50 years old, kind expression, traditional attire",
        "srilankan_mentor_female": "elegant Sri Lankan woman, 50 years old, graceful saree, warm demeanor",
        "srilankan_friend_male": "young Sri Lankan man, 25 years old, modern casual style, friendly vibe",
        "srilankan_friend_female": "young Sri Lankan woman, 25 years old, modern outfit, warm personality",
        "srilankan_romantic_male": "handsome Sri Lankan man, 28 years old, well-groomed, charming",
        "srilankan_romantic_female": "beautiful Sri Lankan woman, 27 years old, elegant style, warm eyes",

        # Emirati personas
        "emirati_mentor_male": "distinguished Emirati man, 50 years old, traditional kandura, wise expression",
        "emirati_mentor_female": "elegant Emirati woman, 50 years old, sophisticated abaya, refined look",
        "emirati_friend_male": "young Emirati man, 25 years old, modern thobe, contemporary style",
        "emirati_friend_female": "young Emirati woman, 25 years old, modern modest fashion, stylish",
        "emirati_romantic_male": "handsome Emirati man, 30 years old, luxury fashion, confident look",
        "emirati_romantic_female": "beautiful Emirati woman, 28 years old, elegant outfit, warm expression",
    }

    return persona_visuals.get(
        bot_id,
        "a person with warm expression, natural lighting, casual outfit"
    )


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# USER + BOT COMPOSITE SELFIE (COMMENTED OUT FOR FUTURE)
# Uncomment when you want to enable user face compositing.
# Requires IP-Adapter-FaceID or InstantID model on HuggingFace.
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# async def generate_composite_selfie(
#     bot_id: str,
#     scene_description: str,
#     user_id: str,
#     user_avatar_url: str,
# ) -> Optional[dict]:
#     """
#     Generate a selfie with BOTH the bot and user faces composited together.
#     Uses IP-Adapter-FaceID for face-preserving generation.
#     
#     Steps:
#     1. Fetch bot face image from Supabase Storage
#     2. Fetch user avatar from Supabase Storage
#     3. Send both faces + scene description to HuggingFace IP-Adapter model
#     4. Upload result to Supabase Storage
#     """
#     settings = get_settings()
#     
#     # Fetch both face images
#     bot_face_filename = get_bot_face_image(bot_id)
#     bot_face_url = get_public_url("bot-faces", bot_face_filename)
#     
#     async with httpx.AsyncClient(timeout=15.0) as client:
#         # Download bot face
#         bot_face_response = await client.get(bot_face_url)
#         bot_face_bytes = bot_face_response.content
#         bot_face_b64 = base64.b64encode(bot_face_bytes).decode("utf-8")
#         
#         # Download user avatar
#         user_face_response = await client.get(user_avatar_url)
#         user_face_bytes = user_face_response.content
#         user_face_b64 = base64.b64encode(user_face_bytes).decode("utf-8")
#     
#     # Build the IP-Adapter request
#     # Note: This requires a HuggingFace model that supports multi-face IP-Adapter
#     # Models to try: "h94/IP-Adapter-FaceID" or similar
#     composite_prompt = (
#         f"Two people taking a selfie together, {scene_description}, "
#         f"natural lighting, high quality portrait photography"
#     )
#     
#     url = f"https://api-inference.huggingface.co/models/h94/IP-Adapter-FaceID"
#     headers = {"Authorization": f"Bearer {settings.HF_API_TOKEN}"}
#     
#     payload = {
#         "inputs": composite_prompt,
#         "parameters": {
#             "face_images": [bot_face_b64, user_face_b64],
#         },
#     }
#     
#     try:
#         async with httpx.AsyncClient(timeout=120.0) as client:
#             response = await client.post(url, headers=headers, json=payload)
#             if response.status_code == 503:
#                 import asyncio
#                 await asyncio.sleep(30)
#                 response = await client.post(url, headers=headers, json=payload)
#             response.raise_for_status()
#             image_bytes = response.content
#         
#         filename = f"selfies/{user_id}/{bot_id}/composite_{uuid.uuid4().hex}.png"
#         image_url = await upload_to_storage("selfies", image_bytes, filename, "image/png")
#         
#         return {
#             "image_url": image_url,
#             "scene_description": scene_description,
#             "includes_user": True,
#         }
#     except Exception as e:
#         logger.error(f"Composite selfie generation failed: {e}")
#         return None
