"""
Veliora.AI — Diary Routes
Read persona diary entries generated by the nightly CRON job.
"""

from fastapi import APIRouter, HTTPException, Depends
import logging
from models.schemas import DiaryResponse, DiaryEntry, DiaryAddRequest
from api.auth import get_current_user
from datetime import datetime

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/diary", tags=["Persona Diary"])

@router.post("/add")
async def add_diary(
    request: DiaryAddRequest,
    current_user: dict = Depends(get_current_user),
):
    """
    Manually add a diary entry from the UI.
    Usually, diaries are generated via CRON, but this handles manual submissions.
    """
    from services.supabase_client import get_supabase
    
    user_id = current_user["user_id"]
    client = get_supabase()
    
    payload = {
        "user_id": user_id,
        "bot_id": request.bot_id,
        "content": request.content,
        "mood": request.mood,
        "entry_date": datetime.utcnow().date().isoformat()
    }
    
    try:
        response = client.table("diary").insert(payload).execute()
        return {"success": True, "inserted": response.data}
    except Exception as e:
        logger.error(f"Error adding diary: {e}")
        raise HTTPException(status_code=500, detail="Failed to add diary entry")



@router.get("/{bot_id}", response_model=DiaryResponse)
async def get_diary(
    bot_id: str,
    limit: int = 30,
    current_user: dict = Depends(get_current_user),
):
    """
    Get the persona's diary entries for the current user.
    
    Diaries are generated nightly by the background CRON job.
    Each entry is written in first-person from the bot's perspective,
    reflecting on the day's conversations with the user.
    """
    from services.supabase_client import get_diary_entries
    from services.background_tasks import award_xp

    user_id = current_user["user_id"]

    entries = await get_diary_entries(user_id, bot_id, limit=limit)

    if not entries:
        return DiaryResponse(
            entries=[],
            xp_earned=0,
        )

    # Award XP for reading diary
    xp_result = await award_xp(user_id, bot_id, "diary_read")

    return DiaryResponse(
        entries=[
            DiaryEntry(
                id=entry.get("id", ""),
                bot_id=entry.get("bot_id", bot_id),
                entry_date=entry.get("entry_date", ""),
                content=entry.get("content", ""),
                mood=entry.get("mood"),
                created_at=entry.get("created_at"),
            )
            for entry in entries
        ],
        xp_earned=xp_result.get("total_earned", 30),
    )
